# version: '3.1'
# Use root/example as user/password credentials
services:
  php:
    #image: php:5.6-apache
    build:
      context: .
      dockerfile: Dockerfile
    container_name: webserver
    ports: 
      - 9000:80
    volumes:
      - ./apache/src:/var/www/html

  db:
    image: mariadb
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    #command: --default-authentication-plugin=mysql_native_password
    restart: always
    container_name: mysqlHost
    ports:
        - 33099:3306
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
    volumes:
      - ./mysql/data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: Myadmin
    restart: always
    ports:
      - 9001:8080
